
package com.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Tue Feb 04 03:24:22 ART 2025
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "getProductos", namespace = "http://ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductos", namespace = "http://ws.com/")

public class GetProductos {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

